bibliophiliac/views/authentication.py
from flask import Blueprint
from flask.globals import request, g, session, current_app
from flask import redirect, url_for, flash, render_template
from sqlalchemy.exc import IntegrityError
from bibliophiliac.views.database import access_database
from werkzeug.security import check_password_hash, generate_password_hash
from functools import wraps
import os, shutil, glob

basedir = os.path.abspath(os.path.dirname(__name__))
bp = Blueprint("authenticate", __name__)


def find_profile_image(filename):
    file = [
        file
        for file in glob.glob(
            os.path.join(basedir + current_app.config["AVATARS_FOLDER"], filename + "*")
        )
    ][0]    
    return file


@bp.route("/register", methods=["GET", "POST"])
def register_user():
    """Handle the register request"""
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        error = None

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."
        elif not error:
            db = access_database()
            try:
                db.execute(
                    "INSERT INTO users (name, password) VALUES (:username, :password)",
                    {
                        "username": username,
                        "password": generate_password_hash(password),
                    },
                )
                db.commit()
                src = basedir + current_app.config["DEFAULT_AVATAR_IMAGE"]
                dest = basedir + current_app.config["AVATARS_FOLDER"]
                default_avatar_image = current_app.config["DEFAULT_AVATAR_IMAGE"].split(
                    "/"
                )[-1]
                old_name = os.path.join(dest, default_avatar_image)
                new_name = os.path.join(dest, username + ".png")
                shutil.copy2(src, dest)
                os.rename(old_name, new_name)
                return redirect(url_for("authenticate.login_user"))
            except IntegrityError:
                error = "Username already taken."

        flash(error)
    else:
        return render_template("log_auth/register.html")


@bp.route("/login", methods=["GET", "POST"])
def login_user():
    """Handle the login request"""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None

        if not username:
            error = "Username required for logging"

        elif not password:
            error = "Password required for logging"
        elif not error:
            db = access_database()
            user_data = db.execute(
                "SELECT * FROM users WHERE name=:name", {"name": username}
            ).fetchone()

            if user_data and check_password_hash(user_data["password"], password):
                session["user_id"] = user_data["id"]
                session["user_name"] = user_data["name"]                
                return redirect(url_for("books.search_for_book"))
            else:
                error = "Wrong username and/or password."
        flash(error)

    return render_template("log_auth/login.html")


@bp.route("/logout")
def logout_user():
    if "user_name" in session:
        session.pop("user_id")
        session.pop("user_name")

    return redirect(url_for("authenticate.login_user"))


@bp.before_app_request
def load_user_information():
    """Get user information and store it for every request duration"""
    if session.get("user_name", None):
        g.username = session["user_name"]
        g.id = session["user_id"]

        if g.username:
            try:
                file = find_profile_image(g.username)
                _, extension = os.path.splitext(file)
                g.profile_url = f"imgs/avatars/{g.username + extension}"
            except:
                pass


def check_user_permission(view):
    """Check if user has priviledges to perform tasks"""

    @wraps(view)
    def wrapper(**kwargs):
        """Check if user information available, if not redirect to
        login.
        """
        if "id" not in g:
            return redirect(url_for("authenticate.login_user"))
        return view(**kwargs)

    return wrapper

bibliophiliac/views/search_and_reviews.py
from flask import Blueprint, redirect, url_for
from flask.globals import request, g, current_app
from flask.helpers import flash
from flask.templating import render_template
from bibliophiliac.views.database import access_database
from bibliophiliac.views.authentication import check_user_permission
import requests
import os, glob

basedir = os.path.abspath(os.path.dirname(__name__))

bp = Blueprint("books", __name__)

api_key = None


def find_profile_image(filename):
    file = [
        file
        for file in glob.glob(
            os.path.join(basedir + current_app.config["AVATARS_FOLDER"], filename + "*")
        )
    ][0]
    return file


def fetch_from_api(isbn):
    global api_key
    if not api_key:
        api_key = current_app.config["BOOKS_API_KEY"]
    try:
        res = requests.get(
            "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                isbn, api_key
            ),
            timeout=30,
        )
        data = res.json()
        book_data = data["items"][0]["volumeInfo"]
        if "imageLinks" in book_data.keys():
            return {
                "average_rating": book_data["averageRating"],
                "total_reviews": book_data["ratingsCount"],
                "description": book_data["description"],
                "image": book_data["imageLinks"]["thumbnail"],
            }
        else:
            return {
                "average_rating": book_data["averageRating"],
                "total_reviews": book_data["ratingsCount"],
                "description": book_data["description"],
                "image": url_for("static", filename="imgs/default_book_image.png"),
            }
    except:
        return {
            "average_rating": "n/a",
            "total_reviews": "n/a",
            "description": "n/a",
            "image": url_for("static", filename="imgs/default_book_image.png"),
        }


def search_books_results_api(books_results):
    if books_results is not None and books_results != []:
        api_data = []
        api_data = []
        for result in books_results:
            try:
                res = requests.get(
                    "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                        result.isbn, api_key
                    ),
                    timeout=30,
                )
                data = res.json()
                books_data = data["items"][0]["volumeInfo"]
                api_data.append(
                    {
                        "description": books_data["description"],
                        "image": books_data["imageLinks"]["thumbnail"],
                    }
                )
            except:
                api_data.append(
                    {
                        "description": "n/a",
                        "image": url_for(
                            "static", filename="imgs/default_book_image.png"
                        ),
                    }
                )
        books_results = zip(books_results, api_data)
    return books_results


def search_book_info(isbn):
    try:
        res = requests.get(
            "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                isbn, api_key
            ),
            timeout=30,
        )
        data = res.json()
        book_data = data["items"][0]["volumeInfo"]
        google_books_data = {
            "average_rating": book_data["averageRating"],
            "total_reviews": book_data["ratingsCount"],
            "description": book_data["description"],
            "image": book_data["imageLinks"]["thumbnail"],
        }
    except:
        google_books_data = {
            "average_rating": "n/a",
            "total_reviews": "n/a",
            "description": "n/a",
            "image": url_for("static", filename="imgs/default_book_image.png"),
        }
    return google_books_data


def search_books_image(books_results):
    api_data = []
    for result in books_results:
        try:
            res = requests.get(
                "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                    result.isbn, api_key
                ),
                timeout=30,
            )
            data = res.json()
            books_data = data["items"][0]["volumeInfo"]
            api_data.append({"image": books_data["imageLinks"]["thumbnail"]})
        except:
            api_data.append(
                {"image": url_for("static", filename="imgs/default_book_image.png")}
            )
    books_results = zip(books_results, api_data)
    return books_results


@bp.route("/search", methods=["GET"])
@check_user_permission  # public books info first if not logged in
def search_for_book():
    message = None
    search_results = None
    is_successful = False

    db = access_database()
    search_filter = request.args.get("search_filter")
    search_query = request.args.get("search_term")
    if search_filter and search_query:
        sql_books_query = "SELECT * FROM books WHERE " + search_filter + " ILIKE :term"
        search_results = db.execute(
            sql_books_query, {"term": f"%{search_query}%"}
        ).fetchall()
        is_successful = True
    elif search_query:
        search_results = db.execute(
            "SELECT * FROM books WHERE isbn ILIKE :term OR "
            + "title ILIKE :term OR "
            + "author ILIKE :term OR "
            + "year ILIKE :term;",
            {"term": f"%{search_query}%"},
        ).fetchall()
        is_successful = True
    if search_results == [] or search_results is None:
        message = f"Search for '{request.args.get('search_filter', '')}: {search_query}' yielded 0 results.".capitalize()
    else:
        search_results = zip(
            search_results, [fetch_from_api(result.isbn) for result in search_results]
        )

    return render_template(
        "reviews/search.html",
        is_successful=is_successful,
        message=message,
        results_list=search_results,
    )


@bp.route("/review/<string:isbn>")
def find_review(isbn):
    db = access_database()
    sql_books_query = "SELECT * FROM books WHERE isbn=:isbn_result"
    book_results = db.execute(sql_books_query, {"isbn_result": isbn}).fetchone()
    book_stats = db.execute(
        "SELECT COUNT(*) AS total_reviews, ROUND(AVG(rating), 1) AS average_rating FROM reviews WHERE book_isbn=:isbn",
        {"isbn": isbn},
    ).fetchone()
    sql_reviews_query = "SELECT * FROM reviews JOIN users ON users.id=reviews.name_id WHERE book_isbn=:isbn_result"
    book_reviews = db.execute(sql_reviews_query, {"isbn_result": isbn}).fetchall()
    modified_book_reviews = []
    for review in book_reviews:
        review_column = dict(review)
        file = find_profile_image(review.name)
        avatar, extension = os.path.splitext(file)
        review_column["name"] = review.name
        review_column["profile_pic"] = review.name + extension
        modified_book_reviews.append(review_column)

    if g.get("id", None):
        sql_review_query = (
            "SELECT * FROM reviews WHERE book_isbn=:isbn_result AND name_id=:id"
        )
        existing_user_review = db.execute(
            sql_review_query, {"isbn_result": isbn, "id": g.id}
        ).fetchone()
        login_user_review_exists = True if existing_user_review else False
    google_books_data = fetch_from_api(isbn)
    if book_results:
        return render_template(
            "reviews/book_reviews.html",
            book_results=book_results,
            book_reviews=modified_book_reviews,
            user_review_exists=login_user_review_exists,
            book_stats=book_stats,
            google_books=google_books_data,
        )
    else:
        flash(f"Book with isbn no: {isbn} not found!")
        return render_template("error.html")


@bp.route("/review/<string:isbn>", methods=["GET", "POST"])
@check_user_permission
def add_review(isbn):
    if request.method == "POST":
        rating = request.form.get("rating")
        opinion = request.form.get("user_review")
        error = None
        if rating == "0":
            error = "Your rating is required!"
        elif not opinion:
            error = "Your review is required!"
        elif not all([int(g.id), int(isbn)]):
            error = "Invalid Request!"
        else:
            db = access_database()
            db.execute(
                "INSERT INTO reviews  (rating, opinion, name_id, book_isbn) VALUES (:rating, :opinion, :id, :isbn)",
                {"rating": rating, "opinion": opinion, "id": g.id, "isbn": isbn},
            )
            db.commit()

        flash(error)

    return redirect(url_for("books.find_review", isbn=isbn))


@bp.route("/your_reviews/<int:id>")
@check_user_permission
def fetch_user_reviews(id):
    db = access_database()
    reviews_list = db.execute(
        "SELECT * FROM reviews JOIN books ON books.isbn=reviews.book_isbn WHERE name_id=:id",
        {"id": id},
    ).fetchall()
    review_stats = db.execute(
        "WITH review_stats AS (SELECT name_id, COUNT(*) AS total_reviews, ROUND(AVG(rating), 1) AS average_rating FROM reviews GROUP BY name_id) SELECT * FROM review_stats WHERE name_id=:id",
        {"id": id},
    ).fetchone()
    message = None
    if reviews_list == []:
        message = "You have no reviews yet"
        average_rating_score = None
    else:
        reviews_list = zip(
            reviews_list, [fetch_from_api(book.isbn) for book in reviews_list]
        )
    return render_template(
        "reviews/my_reviews.html",
        reviews_list=reviews_list,
        message=message,
        review_stats=review_stats,
    )


@bp.route("/all_reviews")
def fetch_all_reviews():
    db = access_database()

bibliophiliac/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="../static/fontawesome-free-5.15.4-web/css/all.css">        -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/utilities.css') }}"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
    {% block stylesheet %} {% endblock %}
    <title>{% block title %} {% endblock %}-Bibliophiliac</title>
</head>
<body>
        
    <div class="site-container">
        <header class="navbar  my-0 py-0 primary-bg">
            <nav class="flex my-0 py-0 fs-2 nav">
                <div class="toggle-side-nav mx-1">
                    <i class="nav-toggle fa fa-caret-right fa-2x" aria-hidden="true"></i>                
                </div>
                <div class="logo">
                    <p>Bibliophiliac</p>
                </div>    
                <div class="account fs-0">                                
                {% if g.id %}                
                    <span class="small-avatar"><img src="{{ url_for('static', filename=g.profile_url) }}" alt="" id="nav-avatar"></span> <button class="username-account primary-bg btn-primary fs-0">{{ g.username }} <i class="fa fa-caret-down" aria-hidden="true"></i> </button>
                        <div class="account-menu">                         
                            <a class="secondary-bg py-1 fs-0" href="{{ url_for('books.fetch_user_reviews', id=g.id) }}">My Reviews</a>
                            <a class="secondary-bg py-1 fs-0" href="{{ url_for('books.fetch_all_reviews') }}">All Reviews</a>
                            <a class="secondary-bg py-1 fs-0" href="{{ url_for('authenticate.logout_user') }}">Logout</a>
                        </div>
                </div>
                <div class="side-nav secondary-bg hide-side-nav" tabindex="1">
                    <form action="{{ url_for('books.search_for_book') }}" method="get" class="nav-search">
                        <input class="fs-2" type="text" name='search_term'>
                        <button class="btn-primary fs-0" type="submit">Book Search</button>
                    </form>
                    <nav class="side-nav-links">
                        <ul class="nav-links fs-1 m-0"> 
                            <li class='py-1'><button class="reviews-btn btn-primary fs-1">Reviews <i class="fa fa-caret-down" aria-hidden="true"></i> </button>
                                <div class="reviews-menu secondary-bg fs-0">
                                    <a class="secondary-bg py-1" href="{{ url_for('books.fetch_user_reviews', id=g.id) }}">My Reviews</a>
                                    <a class="secondary-bg py-1" href="{{ url_for('books.fetch_all_reviews') }}">All Reviews</a>
                                </div>
                            </li>                                                                               
                            <li class='py-1'><a class="secondary-bg  py-1" href="{{ url_for('profile.show_user_profile', name=g.username) }}">My Profile</a></li>                                               
                            <li class="py-1"><a class="secondary-bg py-1" href="{{ url_for('authenticate.logout_user') }}">Sign Out</a></li>
                        </ul>
                    </nav>
                </div>            
            </nav>        
        </header>                            
                {% else %}
                <span class="small-avatar"><img src="{{ url_for('static', filename='imgs/default_avatar.png') }}" alt=""></span><button class="username-account primary-bg btn-primary fs-1">Account <i class="fa fa-caret-down" aria-hidden="true"></i> </button>
                        <div class="account-menu"> 
                            <a class="secondary-bg py-1" href="{{ url_for('authenticate.login_user') }}">Log In</a>
                            <a class="secondary-bg py-1" href="{{ url_for('authenticate.register_user') }}">Register</a>                            
                        </div>
                </div>
                <div class="side-nav secondary-bg hide-side-nav">
                    <form action="{{ url_for('books.search_for_book') }}" method="get" class="nav-search">
                        <input class="fs-2" type="text" name='search_term'>
                        <button class="btn-primary fs-0" type="submit">Book Search</button>
                    </form>
                    <nav class="side-nav-links">
                        <ul class="nav-links fs-1 m-0">                             
                            <li class="py-1"><a class="secondary-bg" href="{{ url_for('authenticate.login_user') }}">Log In</a></li>
                            <li class="py-1"><a class="secondary-bg" href="{{ url_for('authenticate.register_user') }}">Register</a></li>
                        </ul>
                    </nav>
                </div>            
            </nav>        
        </header>
            {% endif %}                              
        <div class="site-body">
            <div class="site-content" tabindex="2">
            {% block content %} {% endblock %}                    
            </div>
            <footer class="site-footer">
                <div>
                    <p>Bibliophiliac</p>
                    <p>Copyright <i class="fa fa-copyright" aria-hidden="true"> 2023</i></p>
                </div>
                <div>            
                    <nav>
                        <ul>
                            {% if g.id %}                
                            <li>  <a href="{{ url_for('books.search_for_book') }}">Book Search</a></li>                            
                            <li><a href="{{ url_for('books.fetch_user_reviews', id=g.id) }}">My Reviews</a></li>
                            <li><a href="{{ url_for('authenticate.logout_user') }}">Sign Out</a></li>                    
                            {% else %}
                            <li><a href="{{ url_for('authenticate.login_user') }}">Log In</a></li>
                            <li><a href="{{ url_for('authenticate.register_user') }}">Register</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div>
                    <p>
                        <i class="fab fa-github fa-2x" aria-hidden="true"></i>
                        <i class="fab fa-twitter fa-2x" aria-hidden="true"></i>
                    </p>
                </div>
            </footer>                        
        </div>           
    </div>

    {% if g.id %}    
    <script>
        let reviewNavButton = document.querySelector('.side-nav-links .nav-links .reviews-btn');
        let profileNavButton = document.querySelector('.side-nav-links .nav-links .profiles-btn');
        let showReviewNavMenu = document.querySelector('.side-nav .side-nav-links .nav-links .reviews-menu');    
        let accountNavButton = document.querySelector('.account .username-account');
        let accountNavMenu = document.querySelector('.account .account-menu');
        let toggleSideNav = document.querySelector('.navbar .flex .toggle-side-nav .nav-toggle');
        let sideNav = document.querySelector('.navbar .flex .side-nav');

        reviewNavButton.addEventListener('click', () => {
            showReviewNavMenu.classList.toggle('show-menu');           
        });    
        accountNavButton.addEventListener('click', () => {
            accountNavMenu.classList.toggle('show-menu');                       
        });

        toggleSideNav.addEventListener('click', () => {
            toggleSideNav.classList.toggle('rotate-toggle') 
            sideNav.classList.toggle('show-side-nav') 
            sideNav.classList.toggle('hide-side-nav')                                             
        });
        document.querySelector('.site-body').addEventListener('click', (event) => {
            // sideNav.classList = sideNav.classList.filter(className => className != 'show-side-nav')
       
            if (Array.from(sideNav.classList).includes('show-side-nav') && event.target.className !== 'side-nav') {
                sideNav.classList.toggle('show-side-nav')                       
                sideNav.classList.toggle('hide-side-nav');
                toggleSideNav.classList.toggle('rotate-toggle');
            }
         
        })
    </script>
    {% else %}
    <script>
    
        let accountNavButton = document.querySelector('.account .username-account');
        let accountNavMenu = document.querySelector('.account .account-menu');
        let toggleSideNav = document.querySelector('.navbar .flex .toggle-side-nav .nav-toggle');
        let sideNav = document.querySelector('.navbar .flex .side-nav');
        
        accountNavButton.addEventListener('click', () => {
            accountNavMenu.classList.toggle('show-menu');                       
        });

        toggleSideNav.addEventListener('click', () => {
            toggleSideNav.classList.toggle('rotate-toggle') 
            sideNav.classList.toggle('show-side-nav')                       
            sideNav.classList.toggle('hide-side-nav')                      
        })
        document.querySelector('.site-body').addEventListener('click', (event) => {                        
            if (Array.from(sideNav.classList).includes('show-side-nav') && event.target.className !== 'side-nav') {
                sideNav.classList.toggle('show-side-nav')                       
                sideNav.classList.toggle('hide-side-nav');
                toggleSideNav.classList.toggle('rotate-toggle');
            }
         
        })        
    </script>
    {% endif %}
    {% block script %} {% endblock %}
</body>
</html>

bibliophiliac/templates/error.html
{% extends 'base.html' %}

{% block stylesheet %} 
<style>
    
        #error {
            background-color: rgb(138, 2, 2);            
            padding: 50px 20px;        
            min-width: min-content;
            max-width: 80%;
            margin: 50px auto;
            text-align: center;
            color: white;
            font-size: 1rem;
            line-height: 1rem;
            border-radius: 10px;
        }        
</style>
{% endblock %}



{% block header %} 
<br>

<h1 style="padding: 10px; text-align: center; margin: 0px auto 10px auto; width: 100%;">{% block title %} Error {% endblock %}</h1>

{% endblock %}    
<br>
{% block content %} 

<div class="col-12 col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-sm-12">    
    
    <div id="error">
        {% for message in get_flashed_messages() %}
            <p><b>Error: </b>{{ message }}</p>

        {% endfor %}
        <p style="width: max-content; margin: 20px auto 0 auto;"><a href="{{ url_for('books.search_for_book') }}" class="btn-primary" style="text-align: center;">Go to Search</a></p>
    </div>

    </div>

{% endblock %}