bibliophiliac/views/profiles.py
from flask import Blueprint, render_template, redirect, flash
from flask.globals import request, g, current_app, session
from flask.helpers import flash, url_for
from sqlalchemy.exc import IntegrityError, ArgumentError
from bibliophiliac.views.database import access_database
from bibliophiliac.views.authentication import check_user_permission
import os, imghdr, requests, glob
from bibliophiliac.views.search_and_reviews import fetch_from_api
from .search_and_reviews import find_profile_image


bp = Blueprint("profile", __name__)
basedir = os.path.abspath(os.path.dirname(__name__))


def search_books_image(books_results):
    api_data = []
    for result in books_results:
        try:
            res = requests.get(
                "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key=AIzaSyDniynUGFYHQi2ooiC-Q9G9PUDvu-TKVbY".format(
                    result.isbn
                )
            )
            data = res.json()
            books_data = data["items"][0]["volumeInfo"]
            api_data.append({"image": books_data["imageLinks"]["thumbnail"]})
        except:
            api_data.append(
                {"image": url_for("static", filename="imgs/Background6.png")}
            )
    books_results = zip(books_results, api_data)
    return books_results


@bp.route("/profile/<string:name>", methods=["GET"])
@check_user_permission
def show_user_profile(name):
    if request.method == "GET":
        can_edit = False
        user_name = name
        try:
            file = find_profile_image(user_name)
            _, extension = os.path.splitext(file)
            profile_image = user_name + extension
        except IndexError:
            flash(f"Username {name} doesn't exist!")
            return render_template("error.html")
        db = access_database()
        error = None
        if name == g.get("username", None):
            try:
                logged_in_user_reviews = db.execute(
                    "SELECT * FROM reviews JOIN books ON books.isbn=reviews.book_isbn WHERE name_id=:id",
                    {"id": g.id},
                ).fetchall()
                review_stats = db.execute(
                    "WITH review_stats AS (SELECT name_id, COUNT(*) AS total_reviews, ROUND(AVG(rating), 1) AS average_rating FROM reviews GROUP BY name_id) SELECT * FROM review_stats WHERE name_id=:id",
                    {"id": g.id},
                ).fetchone()
                user_reviews = logged_in_user_reviews
                can_edit = True
            except ArgumentError:
                error = "Invalid Request"
        elif name:
            try:
                user_reviews = db.execute(
                    "SELECT * FROM users JOIN reviews ON reviews.name_id=users.id JOIN books ON books.isbn=reviews.book_isbn WHERE name=:name",
                    {"name": name},
                ).fetchall()
                review_stats = db.execute(
                    "WITH review_stats AS (SELECT name_id, COUNT(*) AS total_reviews, ROUND(AVG(rating), 1) AS average_rating FROM reviews GROUP BY name_id) SELECT * FROM review_stats JOIN users ON users.id=name_id WHERE users.name=:name",
                    {"name": name},
                ).fetchone()

            except ArgumentError:
                error = "Invalid Request!"

        if error:
            flash(error)
            return render_template("error.html"), 404
        elif user_reviews is not None and user_reviews != []:
            user_reviews = zip(
                user_reviews, [fetch_from_api(book.isbn) for book in user_reviews]
            )

        return render_template(
            "reviews/profile.html",
            user_reviews=user_reviews,
            review_stats=review_stats,
            can_edit=can_edit,
            username=user_name,
            profile_image=profile_image,
        )


def validate_avatar(file_stream):
    header = file_stream.read(512)
    file_stream.seek(0)
    format = imghdr.what(None, header)
    if format:
        return "." + (format if format != "jpeg" else "jpg")
    else:
        return None


def find_profile_image(filename):
    file = [
        file
        for file in glob.glob(
            os.path.join(basedir + current_app.config["AVATARS_FOLDER"], filename + "*")
        )
    ][0]
    return file


@bp.route("/profile/update/<int:id>", methods=["GET", "POST"])
@check_user_permission
def update_profile(id):
    if request.method == "POST":
        current_app.config["MAX_CONTENT_LENGTH"] = 10 * 1000 * 1000
        try:
            db = access_database()
            file = request.files["avatar_photo"]
            replacing_name = request.form.get("new_name")
            oldname = g.username
            if g.username != replacing_name:
                db.execute(
                    "UPDATE users SET name=:name WHERE id=:id",
                    {"name": replacing_name, "id": id},
                )
                db.commit()
                session["user_name"] = replacing_name
                g.username = replacing_name
            if file.filename:
                extension = os.path.splitext(file.filename)[1]
                allowed_extensions = [".jpg", ".jpeg", ".png", ".gif"]
                if (
                    validate_avatar(file.stream) == extension
                    and extension in allowed_extensions
                ):
                    image_file = find_profile_image(oldname)
                    os.remove(image_file)
                    file.save(
                        os.path.join(
                            basedir + current_app.config["AVATARS_FOLDER"],
                            g.username + extension,
                        )
                    )
            elif oldname != g.username:
                file = find_profile_image(oldname)
                avatar, extension = os.path.splitext(file)
                os.rename(
                    os.path.join(
                        basedir + current_app.config["AVATARS_FOLDER"],
                        oldname + extension,
                    ),
                    os.path.join(
                        basedir + current_app.config["AVATARS_FOLDER"],
                        g.username + extension,
                    ),
                )
        except IntegrityError:
            flash(f"Username {g.username} already exists!")
        return redirect(url_for("profile.show_user_profile", name=g.username))

bibliophiliac/views/search_and_reviews.py
from flask import Blueprint, redirect, url_for
from flask.globals import request, g, current_app
from flask.helpers import flash
from flask.templating import render_template
from bibliophiliac.views.database import access_database
from bibliophiliac.views.authentication import check_user_permission
import requests
import os, glob

basedir = os.path.abspath(os.path.dirname(__name__))

bp = Blueprint("books", __name__)

api_key = None


def find_profile_image(filename):
    file = [
        file
        for file in glob.glob(
            os.path.join(basedir + current_app.config["AVATARS_FOLDER"], filename + "*")
        )
    ][0]
    return file


def fetch_from_api(isbn):
    global api_key
    if not api_key:
        api_key = current_app.config["BOOKS_API_KEY"]
    try:
        res = requests.get(
            "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                isbn, api_key
            ),
            timeout=30,
        )
        data = res.json()
        book_data = data["items"][0]["volumeInfo"]
        if "imageLinks" in book_data.keys():
            return {
                "average_rating": book_data["averageRating"],
                "total_reviews": book_data["ratingsCount"],
                "description": book_data["description"],
                "image": book_data["imageLinks"]["thumbnail"],
            }
        else:
            return {
                "average_rating": book_data["averageRating"],
                "total_reviews": book_data["ratingsCount"],
                "description": book_data["description"],
                "image": url_for("static", filename="imgs/default_book_image.png"),
            }
    except:
        return {
            "average_rating": "n/a",
            "total_reviews": "n/a",
            "description": "n/a",
            "image": url_for("static", filename="imgs/default_book_image.png"),
        }


def search_books_results_api(books_results):
    if books_results is not None and books_results != []:
        api_data = []
        api_data = []
        for result in books_results:
            try:
                res = requests.get(
                    "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                        result.isbn, api_key
                    ),
                    timeout=30,
                )
                data = res.json()
                books_data = data["items"][0]["volumeInfo"]
                api_data.append(
                    {
                        "description": books_data["description"],
                        "image": books_data["imageLinks"]["thumbnail"],
                    }
                )
            except:
                api_data.append(
                    {
                        "description": "n/a",
                        "image": url_for(
                            "static", filename="imgs/default_book_image.png"
                        ),
                    }
                )
        books_results = zip(books_results, api_data)
    return books_results


def search_book_info(isbn):
    try:
        res = requests.get(
            "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                isbn, api_key
            ),
            timeout=30,
        )
        data = res.json()
        book_data = data["items"][0]["volumeInfo"]
        google_books_data = {
            "average_rating": book_data["averageRating"],
            "total_reviews": book_data["ratingsCount"],
            "description": book_data["description"],
            "image": book_data["imageLinks"]["thumbnail"],
        }
    except:
        google_books_data = {
            "average_rating": "n/a",
            "total_reviews": "n/a",
            "description": "n/a",
            "image": url_for("static", filename="imgs/default_book_image.png"),
        }
    return google_books_data


def search_books_image(books_results):
    api_data = []
    for result in books_results:
        try:
            res = requests.get(
                "https://www.googleapis.com/books/v1/volumes?q=+isbn:{}&maxResults=1&orderBy=newest&key={}".format(
                    result.isbn, api_key
                ),
                timeout=30,
            )
            data = res.json()
            books_data = data["items"][0]["volumeInfo"]
            api_data.append({"image": books_data["imageLinks"]["thumbnail"]})
        except:
            api_data.append(
                {"image": url_for("static", filename="imgs/default_book_image.png")}
            )
    books_results = zip(books_results, api_data)
    return books_results


@bp.route("/search", methods=["GET"])
@check_user_permission  # public books info first if not logged in
def search_for_book():
    message = None
    search_results = None
    is_successful = False

    db = access_database()
    search_filter = request.args.get("search_filter")
    search_query = request.args.get("search_term")
    if search_filter and search_query:
        sql_books_query = "SELECT * FROM books WHERE " + search_filter + " ILIKE :term"
        search_results = db.execute(
            sql_books_query, {"term": f"%{search_query}%"}
        ).fetchall()
        is_successful = True
    elif search_query:
        search_results = db.execute(
            "SELECT * FROM books WHERE isbn ILIKE :term OR "
            + "title ILIKE :term OR "
            + "author ILIKE :term OR "
            + "year ILIKE :term;",
            {"term": f"%{search_query}%"},
        ).fetchall()
        is_successful = True
    if search_results == [] or search_results is None:
        message = f"Search for '{request.args.get('search_filter', '')}: {search_query}' yielded 0 results.".capitalize()
    else:
        search_results = zip(
            search_results, [fetch_from_api(result.isbn) for result in search_results]
        )

    return render_template(
        "reviews/search.html",
        is_successful=is_successful,
        message=message,
        results_list=search_results,
    )


@bp.route("/review/<string:isbn>")
def find_review(isbn):
    db = access_database()
    sql_books_query = "SELECT * FROM books WHERE isbn=:isbn_result"
    book_results = db.execute(sql_books_query, {"isbn_result": isbn}).fetchone()
    book_stats = db.execute(
        "SELECT COUNT(*) AS total_reviews, ROUND(AVG(rating), 1) AS average_rating FROM reviews WHERE book_isbn=:isbn",
        {"isbn": isbn},
    ).fetchone()
    sql_reviews_query = "SELECT * FROM reviews JOIN users ON users.id=reviews.name_id WHERE book_isbn=:isbn_result"
    book_reviews = db.execute(sql_reviews_query, {"isbn_result": isbn}).fetchall()
    modified_book_reviews = []
    for review in book_reviews:
        review_column = dict(review)
        file = find_profile_image(review.name)
        avatar, extension = os.path.splitext(file)
        review_column["name"] = review.name
        review_column["profile_pic"] = review.name + extension
        modified_book_reviews.append(review_column)

    if g.get("id", None):
        sql_review_query = (
            "SELECT * FROM reviews WHERE book_isbn=:isbn_result AND name_id=:id"
        )
        existing_user_review = db.execute(
            sql_review_query, {"isbn_result": isbn, "id": g.id}
        ).fetchone()
        login_user_review_exists = True if existing_user_review else False
    google_books_data = fetch_from_api(isbn)
    if book_results:
        return render_template(
            "reviews/book_reviews.html",
            book_results=book_results,
            book_reviews=modified_book_reviews,
            user_review_exists=login_user_review_exists,
            book_stats=book_stats,
            google_books=google_books_data,
        )
    else:
        flash(f"Book with isbn no: {isbn} not found!")
        return render_template("error.html")


@bp.route("/review/<string:isbn>", methods=["GET", "POST"])
@check_user_permission
def add_review(isbn):
    if request.method == "POST":
        rating = request.form.get("rating")
        opinion = request.form.get("user_review")
        error = None
        if rating == "0":
            error = "Your rating is required!"
        elif not opinion:
            error = "Your review is required!"
        elif not all([int(g.id), int(isbn)]):
            error = "Invalid Request!"
        else:
            db = access_database()
            db.execute(
                "INSERT INTO reviews  (rating, opinion, name_id, book_isbn) VALUES (:rating, :opinion, :id, :isbn)",
                {"rating": rating, "opinion": opinion, "id": g.id, "isbn": isbn},
            )
            db.commit()

        flash(error)

    return redirect(url_for("books.find_review", isbn=isbn))


@bp.route("/your_reviews/<int:id>")
@check_user_permission
def fetch_user_reviews(id):
    db = access_database()
    reviews_list = db.execute(
        "SELECT * FROM reviews JOIN books ON books.isbn=reviews.book_isbn WHERE name_id=:id",
        {"id": id},
    ).fetchall()
    review_stats = db.execute(
        "WITH review_stats AS (SELECT name_id, COUNT(*) AS total_reviews, ROUND(AVG(rating), 1) AS average_rating FROM reviews GROUP BY name_id) SELECT * FROM review_stats WHERE name_id=:id",
        {"id": id},
    ).fetchone()
    message = None
    if reviews_list == []:
        message = "You have no reviews yet"
        average_rating_score = None
    else:
        reviews_list = zip(
            reviews_list, [fetch_from_api(book.isbn) for book in reviews_list]
        )
    return render_template(
        "reviews/my_reviews.html",
        reviews_list=reviews_list,
        message=message,
        review_stats=review_stats,
    )


@bp.route("/all_reviews")
def fetch_all_reviews():
    db = access_database()

bibliophiliac/templates/reviews/book_reviews.html
{% extends 'base.html' %}

{% block stylesheet %} 
<link rel="stylesheet" href="{{ url_for('static', filename='css/book_reviews.css') }}">
{% endblock %}

{% block title %}Reviews{% endblock %}

{% block content %} 

    <section class="container book-review-stats">        
        <h1 class="review-header card fs-2">Review Stats</h1>
        <div class="review-info card" id="stats">                            
            <div class="img px-1">
                <img src="{{ google_books.image }}" alt="">
            </div>
            <div class="info px-1 ">
                <table >
                    <tr><th>Title</th><td>: </td><td>{{ book_results.title }}</td></tr>
                    <tr><th>Author(s)</th><td>: </td><td>{{ book_results.author }}</td></tr>
                    <tr><th>ISBN</th><td>: </td><td>{{ book_results.isbn }}</td></tr>
                    <tr><th>Year</th><td>: </td><td>{{ book_results.year }}</td></tr>                    
                </table>                
            </div>
            <div class="review-stats p-1">                    
                <div class="review-stats-table ">                        
                    <table class="card">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Bibliophilia</th>
                                <th>Google Books</th>
                            </tr>
                            
                        </thead>
                        <tbody>                                                            
                                {% if book_reviews is sequence %}                                                                
                            <tr>
                                <th>Number of Reviews</th>
                                <td>{{ book_stats.total_reviews }}</td>                                                                
                                <td>{{ google_books.total_reviews }}</td>
                            </tr>
                            <tr>
                                <th>Average Rating</th>                                
                                <td>{{ book_stats.average_rating }}</td>                                                                                                
                                <td>{{ google_books.average_rating }}</td>
                            </tr>
                            
                            {% else %}
                            <tr>
                                <th>Number of Reviews</th>
                                <td>0</td>                                                                
                                <td>{{ google_books.total_reviews }}</td>
                            </tr>
                            <tr>
                                <th>Average Rating</th>                                
                                <td>0</td>                                                                                                
                                <td>{{ google_books.average_rating }}</td>
                            </tr>
                                {% endif %}                            
                        </tbody>
                    </table>
                </div>
                
            </div>
            <div class="description-sect p-1">
                <button class="btn-secondary description-btn">Book Description <i class="fas fa-caret-down    "></i></button>
                <div class="description">
                    <p class="p-1 fs-0">{{ google_books.description }}</p>
                </div>
                
            </div>
        </div>    
    </section>
    <section class="container review">            
        {% if book_reviews %}            
        <h1 class="review-header fs-1 card">Reviews</h1>        
        <div class="book-reviews">  
        {% for review in book_reviews %}
            <div class="users-reviews card">
                <div class="user-avatar">
                    <img src="{{ url_for('static', filename='imgs/avatars/'+review.profile_pic) }}" alt="">
                </div>
                <div class="user-name">                    
                    <p><a href="{{ url_for('profile.show_user_profile', name=review.name) }}">{{ review.name }}</a></p>
                </div>
                <div class="user-review">
                    <p class="fs-2"> <img src="{{ url_for('static', filename='imgs/ratings/rating_{}.png'.format(review.rating)) }}" alt="">  {{ review.rating }}</p>
                    
                </div>
                <div class="user-review-text">
                    <p>
                        {{ review.opinion }}
                    </p>
                </div>
            </div>        
            
        {% endfor %}
        </div>        
        {% else %}
        <h1 class="review-header fs-1 card">No reviews.</h1>        
        {% endif %}
        
        {% if not user_review_exists %}
        <div>        
        {% for message in get_flashed_messages() %}
            {% if message %} 
            <div class="card" role="alert">
            <strong>
                {{ message }}
            </strong>
            </div>
            {% endif %}            
            {% endfor %}
            <div class="review-add card">
                <button id="review-add-btn" class="btn-secondary" onclick="show_review()"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Review</button>
                <div class="review_form">
            
                <form action="{{ url_for('books.add_review', isbn=book_results.isbn) }}" class="form-review" method="post">
                    <div id="star-container" class="form-row">
                        
                        <div class="reviews">
                            
                            <input type="radio" name="rating" id="rate-0" class="review-input review-input-none" value="0" checked>
                            <label class="review-label review-label-zero" for="rate-0">
                                <i class="no-star fa fa-vote-yea"></i>                
                            </label>
                            <input type="radio" name="rating" id="rate-1" class="review-input review-input-one" value="1">
                            <label class="review-label review-label-one" for="rate-1">                
                                <i class="star fa fa-star"></i>
                                <i class="fas fa-angry" style="font-size: 1.5em;"></i>
                            </label>
                            <input type="radio" name="rating" id="rate-2" class="review-input review-input-two" value="2">
                            <label class="review-label review-label-two" for="rate-2">
                                <i class="star fa fa-star"></i>
                                <i class="fas fa-frown" style="font-size: 1.5em;"></i>
                            </label>
                            <input type="radio" name="rating" id="rate-3" class="review-input review-input-three" value="3">
                            <label class="review-label review_label-three" for="rate-3">
                                <i class="star fa fa-star"></i>
                                <i class="fas fa-meh-rolling-eyes" style="font-size: 1.5em;"></i>
                            </label>
                
                            <input type="radio" name="rating" id="rate-4" class="review-input review-input-four" value="4">
                            <label class="review-label review-label-four" for="rate-4">                
                                <i class="star fa fa-star"></i>
                                <i class="fas fa-grin-beam" style="font-size: 1.5em;"></i>    
                            </label>
                            <input type="radio" name="rating" id="rate-5" class="review-input review-input-five" value="5">
                            <label class="review-label review-label-five" for="rate-5">                
                                <i class="star fa fa-star"></i>
                                <i class="fas fa-grin-hearts"  style="font-size: 1.5em;"></i>
                            </label>            
                        
                        </div>
                    </div>
                    <div>
                        <textarea class="review-text" name="user_review" id="" rows="5"></textarea>
                    </div>
                    <div>
                        <button type="submit" class="btn-primary"> Submit Review </button>
                    </div>
                </form>
                </div>
            </div>
        </div>            
    {% endif %}
</section>    



{% endblock %}

{% block script %}
<script>        
    let bookDescriptionToggleButton = document.querySelector('.description-btn');
    
    let descriptionText = document.querySelector('.description');

    
    bookDescriptionToggleButton.addEventListener('click', () => {
            descriptionText.classList.toggle('show-description');
            let textContent = bookDescriptionToggleButton.innerHTML            
            if (textContent.includes("fa-caret-down")) {
                textContent = textContent.replace('down','up')
            }
            else if (textContent.includes("fa-caret-up")) {
                textContent = textContent.replace('up',"down")
            }
            bookDescriptionToggleButton.innerHTML = textContent;
    });
    
    let addReviewButton = document.querySelector('.review-add');        
    
    let textInButton = document.getElementById('review-add-btn')
    function show_review() {
        addReviewButton.classList.toggle('review-show')
        let textContent = textInButton.innerHTML            
        if (textContent.includes("fa-plus")) {
            textContent = textContent.replace('fa-plus','fa-minus')
        }
        else if (textContent.includes("fa-minus")) {
            textContent = textContent.replace('fa-minus',"fa-plus")
        }
        textInButton.innerHTML = textContent
    }

</script>

{% endblock %}

bibliophiliac/templates/reviews/my_reviews.html
{% extends 'base.html' %}

{% block stylesheet %} 
<link rel="stylesheet" href="{{ url_for('static', filename='css/my_reviews.css') }}">
{% endblock %}


{% block title %} My Reviews List {% endblock %}
{% block content %} 

<section class='container'>    
    {% if reviews_list %}
    
    <div class="results-grid">
        <div class="user-reviews-stats card">                        
            <table class="reviews-profile card">
                <tbody>
                    
                    <tr><th>Number of Reviews</th><td>:</td><td>{{ review_stats.total_reviews }}</td></tr>
                    <tr><th>Total Ratings Average</th><td>:</td><td>{{ review_stats.average_rating }}</td></tr>
                </tbody>
            </table>
        </div>
        
            {% for review, images in reviews_list %}                
            <a href="{{ url_for('books.find_review', isbn=review.isbn) }}" class="user-reviewed-books card">            
                <div class="img px-1">
                    <img src="{{ images.image }}" alt="">
                </div>
                <div class="info px-1">
                    <table>
                        <tr><th>Title</th><td>: </td><td>{{ review.title }}</td></tr>
                        <tr><th>Author(s)</th><td>: </td><td>{{ review.author }}</td></tr>                                
                        <tr><th>Year</th><td>: </td><td>{{ review.year }}</td></tr>
                    </table>                    
                </div>  
                <div class="user-review">                    
                    <p class="fs-1">Your Rating: {{ review.rating }} <img src="{{ url_for('static', filename='imgs/ratings/rating_{}.png'.format(review.rating)) }}" alt=""></p>                            
                    
                </div>                      
            </a>     
            {% endfor %}                                               

    </div>
    {% else %} 

    <div class="alert-card card" role="alert">                            
        <p class="fs-0">No Reviews Available. Search for books to review <a href="{{ url_for('books.search_for_book') }}" class="btn-primary">here</a></p>
    </div>
    {% endif %}
    </section>

    

{% endblock %}

bibliophiliac/templates/reviews/reviews_list.html
{% extends 'base.html' %}

{% block stylesheet %} 
<link rel="stylesheet" href="{{ url_for('static', filename='css/search_results.css') }}">
{% endblock %}


{% block title %} Reviews List {% endblock %}
{% block header %} 
<br>
{% if g.id %}
<h1 style="padding: 10px; text-align: center; margin: 0px auto 10px auto; width: 100%;">Your Reviews</h1>
{% else %} 
<h1 style="padding: 10px; text-align: center; margin: 0px auto 10px auto; width: 100%;">All Reviews</h1>
{% endif %}
{% endblock %}    
<br>
{% block content %} 

<div class="col-12 col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-sm-12">    
    
<div class="results_view">
    
    {% if reviews_list %}
    <h3 style="padding: 10px; text-align: center; margin: 10px auto; width: 100%;">Total Books Reviewed: {{ total }}</q></h3>
    <div class="grid_results"> 
    {% for review in reviews_list %}
    
        <a class="flex_results" href="{{ url_for('books.find_review', isbn=review.book_isbn) }}">
            <p><img src="{{ url_for('static', filename='imgs/Background6.png') }}" alt=""></p>
            <ul>
                <li> <b>Title:</b>   {{ review.title }}</li>
                <li><b>Author:</b> {{ review.author }}</li>
                <li><b>Year:</b> {{ review.year }}</li>           
                <li><b>ISBN:</b> {{ review.isbn }}</li>     
                <!-- <li>Average Rating</li> -->
                <!-- <li>Num Responses</li> -->
            </ul>
        </a>
    {% endfor %}

    {% else %}   
    <h4 style="padding: 10px; text-align: center; margin: 10px auto; width: 100%;">{{ message }}</h4>        
    {% endif %}
    </div>
</div>

{% endblock %}